name: Release

on:
  push:
    tags:
      - '*'

jobs:

  # publish-java:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Maven Central Repository
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'temurin'
  #         cache: maven
  #         server-id: ossrh
  #         server-username: MAVEN_USERNAME
  #         server-password: MAVEN_PASSWORD
  #         gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  #         gpg-passphrase: MAVEN_GPG_PASSPHRASE
  #     - name: Publish package
  #       run: mvn --batch-mode -Prelease -Djgitver.use-version="$GITHUB_REF_NAME" deploy
  #       working-directory: java
  #       env:
  #         MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  #         MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #         MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  publish-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Set the version
        working-directory: typescript
        run: cat <<< $(jq -r ".version = \"${$GITHUB_REF_NAME}\"" package.json) > package.json
      - name: Install dependencies and build
        working-directory: typescript
        run: npm ci && npm run clean && npm run build
      - name: Publish package on NPM
        working-directory: typescript
        run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}