name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - java
          - python
    steps:
      # Language specific setup

      # Java setup
      - name: Set up JDK 11
        if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Install jbang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH

      # Python setup
      - name: Install Poetry
        uses: snok/install-poetry@v1

      # Common testing
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tests on ${{ matrix.language }}
        run: ./tests/test.sh ${{ matrix.language }}
