name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - java
          - python
          - typescript
    steps:
      - name: Common - Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      # Language specific setup

      # Java setup
      - name: Java - Set up JDK 11
        if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Java - Install jbang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH

      # Python setup
      - name: Python - Install Poetry
        if: matrix.language == 'python'
        uses: snok/install-poetry@v1
      - name: Python - Add Poetry to PATH
        if: matrix.language == 'python'
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v3
        if: matrix.language == 'typescript'
        with:
          node-version: 18

      # Common testing
      - name: Common - Run Tests for ${{ matrix.language }}
        run: ./tests/test.sh ${{ matrix.language }}
